import Formalization.RuzsaFreiman.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

open scoped Pointwise
open scoped BigOperators

set_option linter.unusedSectionVars false

/-!
# Generalized Arithmetic Progressions & Freiman Homomorphisms

This module formalizes Generalized Arithmetic Progressions (GAPs) and Freiman homomorphisms,
the central structural objects in additive combinatorics (Gregory Freiman 1966, Imre Z. Ruzsa 1994).

## Mathematical Overview

### Generalized Arithmetic Progressions (GAP)
A $d$-dimensional Generalized Arithmetic Progression (GAP) in an additive abelian group $G$ is a set
of the form:
$$P(x_0; v_1, \dots, v_d; N_1, \dots, N_d) = \left\{ x_0 + \sum_{i=1}^d k_i v_i : 0 \le k_i < N_i \right\}$$
where $x_0 \in G$ is the base point, $v_i \in G$ are the step vectors, and $N_i \in \mathbb{N}$ are the side lengths.

1. **Volume Bound**: The cardinality of the GAP is bounded by the product of its dimensions:
   $$|P| \le \prod_{i=1}^d N_i$$
2. **Properness**: A GAP is called **proper** if all $\prod_{i=1}^d N_i$ combinations evaluate to distinct elements,
   i.e., $|P| = \prod_{i=1}^d N_i$.

### Freiman Homomorphisms and Isomorphisms
Let $A \subseteq G$ and $B \subseteq H$ be subsets of abelian groups.
1. A map $\phi : A \to H$ is a **Freiman homomorphism of order $k$** (or Freiman $k$-homomorphism) if for all
   $x_1, \dots, x_k, y_1, \dots, y_k \in A$:
   $$\sum_{i=1}^k x_i = \sum_{i=1}^k y_i \implies \sum_{i=1}^k \phi(x_i) = \sum_{i=1}^k \phi(y_i)$$
2. $\phi$ is a **Freiman isomorphism of order $k$** if it is a bijective Freiman $k$-homomorphism whose inverse
   $\phi^{-1} : \phi(A) \to A$ is also a Freiman $k$-homomorphism.

### Difference Sets and Bogolyubov Configurations
For any non-empty finite set $A$, $0 \in A - A$ and $0 \in (A + A) - (A + A)$, establishing nonemptiness
of the Bogolyubov 4-sumset.

## Formalization Structure

- `GAP`: Structure defining a multi-dimensional Generalized Arithmetic Progression.
- `gapElements`: The finite set of elements generated by a GAP.
- `gapElements_card_le`: The fundamental volume inequality $|P| \le \prod N_i$.
- `isProperGAP`: Predicate for properness of a GAP.
- `IsFreimanHomomorphism`: Definition of Freiman $k$-homomorphism.
- `freimanHomomorphism_id`: The identity map is a Freiman homomorphism of any order $k$.
- `freimanHomomorphism_comp`: Composition of Freiman homomorphisms is a Freiman homomorphism.
- `IsFreimanIsomorphism`: Definition of Freiman $k$-isomorphism.
- `zero_mem_diffset_self`: Zero is an element of $A - A$.
- `zero_mem_bogolyubov`: Zero is an element of the Bogolyubov 4-sumset $(A + A) - (A + A)$.
- `bogolyubov_set_nonempty`: Non-emptiness of $(A + A) - (A + A)$.

## References

- Freiman, G. A. (1966). *Foundations of a Structural Theory of Set Addition*. Kazan Gos. Ped. Inst.
- Ruzsa, I. Z. (1994). *Generalized arithmetical progressions and sumsets*. Acta Mathematica Hungarica, 65(4), 379–388.
- Tao, T., & Vu, V. (2006). *Additive Combinatorics*. Cambridge Studies in Advanced Mathematics.
-/

namespace RuzsaFreiman

/-- A Generalized Arithmetic Progression (GAP) of dimension `dim` in an additive group $G$. -/
structure GAP (G : Type*) [AddCommGroup G] where
  dim : ℕ
  base : G
  steps : Fin dim → G
  lengths : Fin dim → ℕ

/-- The Finset of elements represented by a GAP $P$. -/
def gapElements {G : Type*} [DecidableEq G] [AddCommGroup G] (P : GAP G) : Finset G :=
  (Fintype.piFinset (fun i : Fin P.dim => Finset.range (P.lengths i))).image
    (fun (k : Fin P.dim → ℕ) => P.base + ∑ i : Fin P.dim, (k i) • (P.steps i))

/-- The cardinality of a GAP is bounded by the volume (product of side lengths). -/
theorem gapElements_card_le {G : Type*} [DecidableEq G] [AddCommGroup G] (P : GAP G) :
    (gapElements P).card ≤ ∏ i : Fin P.dim, P.lengths i := by
  dsimp [gapElements]; exact Finset.card_image_le.trans (by simp)

/-- A GAP is proper if all linear combinations evaluate to distinct elements of $G$. -/
def isProperGAP {G : Type*} [DecidableEq G] [AddCommGroup G] (P : GAP G) : Prop :=
  (gapElements P).card = ∏ i : Fin P.dim, P.lengths i

/-- A map $\phi : A \to B$ is a Freiman homomorphism of order $k$ if it preserves $k$-term equality of sums. -/
def IsFreimanHomomorphism {G H : Type*} [AddCommGroup G] [AddCommGroup H]
    (A : Finset G) (f : G → H) (k : ℕ) : Prop :=
  ∀ (xs ys : Fin k → G), (∀ i, xs i ∈ A) → (∀ i, ys i ∈ A) →
    (∑ i, xs i = ∑ i, ys i) → (∑ i, f (xs i) = ∑ i, f (ys i))

/-- Identity map is always a Freiman homomorphism of any order $k$. -/
theorem freimanHomomorphism_id {G : Type*} [AddCommGroup G] (A : Finset G) (k : ℕ) :
    IsFreimanHomomorphism A id k :=
  fun _ _ _ _ => id

/-- Composition of Freiman homomorphisms is a Freiman homomorphism. -/
theorem freimanHomomorphism_comp {G H K : Type*} [AddCommGroup G] [AddCommGroup H] [AddCommGroup K] [DecidableEq H]
    (A : Finset G) (f : G → H) (g : H → K) (k : ℕ)
    (hf : IsFreimanHomomorphism A f k)
    (hg : IsFreimanHomomorphism (A.image f) g k) :
    IsFreimanHomomorphism A (g ∘ f) k :=
  fun xs ys hxs hys h =>
    hg (f ∘ xs) (f ∘ ys) (fun i => Finset.mem_image_of_mem f (hxs i))
      (fun i => Finset.mem_image_of_mem f (hys i)) (hf xs ys hxs hys h)

/-- A map $\phi : A \to B$ is a Freiman isomorphism of order $k$ if it is a Freiman homomorphism with an inverse. -/
def IsFreimanIsomorphism {G H : Type*} [AddCommGroup G] [AddCommGroup H] [DecidableEq H]
    (A : Finset G) (f : G → H) (k : ℕ) : Prop :=
  IsFreimanHomomorphism A f k ∧
  ∃ (g : H → G), IsFreimanHomomorphism (A.image f) g k ∧
    ∀ x ∈ A, g (f x) = x

/-- Zero is in the difference set of any nonempty set. -/
theorem zero_mem_diffset_self {G : Type*} [DecidableEq G] [AddCommGroup G]
    {A : Finset G} (hA : A.Nonempty) : (0 : G) ∈ A - A :=
  let ⟨a, ha⟩ := hA; Finset.mem_sub.2 ⟨a, ha, a, ha, sub_self a⟩

/-- Zero is in the Bogolyubov 4-sumset $(A + A) - (A + A)$ for any nonempty $A$. -/
theorem zero_mem_bogolyubov {G : Type*} [DecidableEq G] [AddCommGroup G]
    {A : Finset G} (hA : A.Nonempty) : (0 : G) ∈ ((A + A) - (A + A)) :=
  zero_mem_diffset_self (hA.add hA)

/-- Nonemptiness of the Bogolyubov 4-sumset $(A + A) - (A + A)$ for nonempty $A$. -/
theorem bogolyubov_set_nonempty {G : Type*} [DecidableEq G] [AddCommGroup G]
    {A : Finset G} (hA : A.Nonempty) : ((A + A) - (A + A)).Nonempty :=
  ⟨0, zero_mem_bogolyubov hA⟩

end RuzsaFreiman
