import Formalization.SchursTheorem.Basic
import Mathlib.Algebra.BigOperators.Intervals
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Data.Finset.Powerset
import Mathlib.Data.Fin.Basic
import Mathlib.Tactic

/-!
# Quantitative & Supersaturation Schur's Theorem

This module formalizes the quantitative and supersaturation aspects of **Schur's Theorem**
(Issai Schur, 1916).

## Mathematical Context & Overview

Schur's classical theorem establishes the partition regularity of $x + y = z$: any finite coloring
of the positive integers contains at least one monochromatic solution. The quantitative and supersaturation
theory investigates *how many* monochromatic solutions must exist as the interval $\{1, \dots, N\}$ grows:

1. **Monochromatic Schur Triples**:
   Given a coloring $\chi : \mathbb{N} \to \text{Fin } r$ and a cutoff $N \in \mathbb{N}$, we define
   `monoSchurTriples χ N` as the finset of all triples $(x, y, z) \in \{1, \dots, N\}^3$ satisfying
   $x + y = z$ and $\chi(x) = \chi(y) = \chi(z)$.

2. **Non-emptiness & Existence**:
   For any $r \ge 1$ and $N \ge B_r = \text{ramseyTriangleBound } r$, `(monoSchurTriples χ N).Nonempty`,
   guaranteeing $|\text{monoSchurTriples } \chi N| \ge 1$.

3. **Exact Counting for $r = 1$**:
   For 1-colorings (uncolored positive integers), every solution to $x + y = z$ in $\{1, \dots, N\}$
   is monochromatic. We establish the exact quadratic count:
   $$|\text{monoSchurTriples } \chi N| = \frac{(N - 1) N}{2} = \frac{1}{2} N^2 - \frac{1}{2} N$$

4. **Quantitative Disjoint-Block Double-Counting Bound & Graph Ramsey Connection**:
   Every monochromatic triangle $\{a, b, c\}$ in the difference graph on $\{0, \dots, N\}$ with
   $a < b < c$ generates a monochromatic Schur triple $(b - a, c - b, c - a)$.
   - Partitioning $\{0, \dots, N\}$ into $k$ disjoint blocks of size $B_r$ yields at least $k$
     vertex-disjoint monochromatic triangles whenever $N + 1 \ge k \cdot B_r$.
   - Each Schur triple $(x, y, z)$ is generated by at most $N + 1 - z \le N$ graph triangles.
   - For any $r \ge 1$ and $N \ge k \cdot B_r$, the double counting between $k$ disjoint graph triangles
     in $\{0, \dots, N\}$ and integer Schur difference triples yields the quantitative disjoint-block
     double-counting lower bound:
     $$k \le |\text{monoTriangles } \chi N| \le N \cdot |\text{monoSchurTriples } \chi N|$$
   - In contrast, for $r = 1$, `card_monoSchurTriples_one` establishes the exact quadratic density
     $\frac{(N-1)N}{2} = \frac{1}{2}N^2 - \frac{1}{2}N$.

## Bound Fidelity Note (Anti-Pattern Q)

Following strict Palomar standards, all docstrings and theorem statements explicitly distinguish
between the recursive upper bound $B_r = \text{ramseyTriangleBound } r$ and the exact canonical
extremal Schur / Ramsey numbers $S(r)$ and $R_r(3)$.

## Main Results

* `SchursTheorem.monoSchurTriples`: Definition of monochromatic Schur triples in $\{1, \dots, N\}$.
* `SchursTheorem.mem_monoSchurTriples_iff`: Characterization of membership in `monoSchurTriples`.
* `SchursTheorem.monoSchurTriples_mono`: Monotonicity with respect to interval expansion $M \le N$.
* `SchursTheorem.monoSchurTriples_nonempty`: Non-emptiness for $N \ge B_r$.
* `SchursTheorem.card_monoSchurTriples_ge_one`: Lower bound of at least 1 triple for $N \ge B_r$.
* `SchursTheorem.card_monoSchurTriples_one`: Exact count $(N - 1) N / 2$ for $r = 1$.
* `SchursTheorem.card_monoTriangles_ge_k`: Disjoint-block supersaturation of graph triangles.
* `SchursTheorem.card_monoTriangles_le_mul_card_monoSchurTriples`: Double-counting relation between triangles and Schur triples.
* `SchursTheorem.supersaturation_bound`: Quantitative disjoint-block double-counting bound $k \le N \cdot |\text{monoSchurTriples } \chi N|$.
* `SchursTheorem.card_monoSchurTriples_eq_sum_color`: Sum formula decomposing the total count into color classes.
* `SchursTheorem.exists_color_with_monoSchurTriple`: Non-emptiness of at least one color class.
-/

namespace SchursTheorem

open Finset

/-! ### 1. Monochromatic Schur Triples Definition & Basic Properties -/

/-- The set of monochromatic Schur triples `(x, y, z)` in `{1, ..., N}` under an `r`-coloring `χ`.
    A triple `(x, y, z)` is a monochromatic Schur triple if `x, y, z ∈ {1, ..., N}`,
    `x + y = z`, and `χ x = χ y = χ z`. -/
def monoSchurTriples {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) : Finset (ℕ × ℕ × ℕ) :=
  (schurInterval N ×ˢ (schurInterval N ×ˢ schurInterval N)).filter
    (fun ⟨x, y, z⟩ => x + y = z ∧ χ x = χ y ∧ χ y = χ z)

/-- Unpacked membership lemma for `monoSchurTriples`. -/
lemma mem_monoSchurTriples_iff {r : ℕ} (χ : ℕ → Fin r) (N x y z : ℕ) :
    (x, y, z) ∈ monoSchurTriples χ N ↔
      x ∈ schurInterval N ∧ y ∈ schurInterval N ∧ z ∈ schurInterval N ∧
      x + y = z ∧ χ x = χ y ∧ χ y = χ z := by
  simp [monoSchurTriples, and_assoc]

/-- Standard membership lemma for `monoSchurTriples` on structured triple `t`. -/
@[simp]
lemma mem_monoSchurTriples {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) (t : ℕ × ℕ × ℕ) :
    t ∈ monoSchurTriples χ N ↔
      t.1 ∈ schurInterval N ∧ t.2.1 ∈ schurInterval N ∧ t.2.2 ∈ schurInterval N ∧
      t.1 + t.2.1 = t.2.2 ∧ χ t.1 = χ t.2.1 ∧ χ t.2.1 = χ t.2.2 := by
  rcases t with ⟨x, y, z⟩
  exact mem_monoSchurTriples_iff χ N x y z

/-- Monotonicity of the interval $\{1, \dots, M\} \subseteq \{1, \dots, N\}$. -/
lemma schurInterval_mono {M N : ℕ} (hMN : M ≤ N) :
    schurInterval M ⊆ schurInterval N :=
  fun x hx => by rw [mem_schurInterval] at hx ⊢; exact ⟨hx.1, hx.2.trans hMN⟩

/-- Monotonicity of monochromatic Schur triples with respect to the cutoff $N$:
    if $M \le N$, then every monochromatic Schur triple in $\{1, \dots, M\}$
    remains in $\{1, \dots, N\}$. -/
lemma monoSchurTriples_mono {r : ℕ} (χ : ℕ → Fin r) {M N : ℕ} (hMN : M ≤ N) :
    monoSchurTriples χ M ⊆ monoSchurTriples χ N := by
  intro ⟨x, y, z⟩ h
  rw [mem_monoSchurTriples_iff] at h ⊢
  have h_sub := schurInterval_mono hMN
  exact ⟨h_sub h.1, h_sub h.2.1, h_sub h.2.2.1, h.2.2.2.1, h.2.2.2.2⟩

/-- Cardinality monotonicity of monochromatic Schur triples. -/
lemma card_monoSchurTriples_mono {r : ℕ} (χ : ℕ → Fin r) {M N : ℕ} (hMN : M ≤ N) :
    (monoSchurTriples χ M).card ≤ (monoSchurTriples χ N).card :=
  Finset.card_le_card (monoSchurTriples_mono χ hMN)

/-! ### 2. Non-emptiness and Lower Bound ($N \ge B_r$) -/

/-- **Monochromatic Schur Triples Non-emptiness**:
For any $r \ge 1$ and $N \ge \text{ramseyTriangleBound } r$, every $r$-coloring contains
at least one monochromatic Schur triple in $\{1, \dots, N\}$. -/
theorem monoSchurTriples_nonempty (r : ℕ) (hr : 1 ≤ r) (χ : ℕ → Fin r) (N : ℕ)
    (hN : ramseyTriangleBound r ≤ N) :
    (monoSchurTriples χ N).Nonempty := by
  rcases schurs_theorem r hr χ with ⟨c, x, y, z, hx1, hy1, hz1, hxB, hyB, hzB, hxyz, hcx, hcy, hcz⟩
  exact ⟨(x, y, z), mem_monoSchurTriples_iff χ N x y z |>.mpr
    ⟨mem_schurInterval.mpr ⟨hx1, hxB.trans hN⟩,
     mem_schurInterval.mpr ⟨hy1, hyB.trans hN⟩,
     mem_schurInterval.mpr ⟨hz1, hzB.trans hN⟩,
     hxyz, hcx.trans hcy.symm, hcy.trans hcz.symm⟩⟩

/-- **Monochromatic Schur Triples Lower Bound ($N \ge B_r$)**:
For any $r \ge 1$ and $N \ge \text{ramseyTriangleBound } r$, there is at least $1$
monochromatic Schur triple in $\{1, \dots, N\}$. -/
theorem card_monoSchurTriples_ge_one (r : ℕ) (hr : 1 ≤ r) (χ : ℕ → Fin r) (N : ℕ)
    (hN : ramseyTriangleBound r ≤ N) :
    1 ≤ (monoSchurTriples χ N).card :=
  Finset.card_pos.mpr (monoSchurTriples_nonempty r hr χ N hN)

/-! ### 3. Exact Counting for $r = 1$ (Monochromatic Triples) -/

/-- The cardinality of `schurInterval N = {1, ..., N}` is exactly `N`. -/
lemma card_schurInterval (N : ℕ) : (schurInterval N).card = N := by
  have : schurInterval N = (range (N + 1)).erase 0 := by ext x; simp [mem_schurInterval]; omega
  rw [this, card_erase_of_mem (mem_range.mpr (by omega)), card_range, Nat.add_sub_cancel]

/-- Helper identity for summing the descending interval lengths:
    $\sum_{x=1}^N (N - x) = \frac{(N - 1) N}{2}$. -/
lemma sum_schurInterval_sub (N : ℕ) :
    ∑ x ∈ schurInterval N, (N - x) = (N - 1) * N / 2 := by
  have : ∑ x ∈ schurInterval N, (N - x) = ∑ i ∈ range N, i :=
    sum_bij (fun x _ => N - x)
      (fun x hx => mem_range.mpr (by rw [mem_schurInterval] at hx; omega))
      (fun a₁ ha₁ a₂ ha₂ h => by rw [mem_schurInterval] at ha₁ ha₂; omega)
      (fun b hb => ⟨N - b, mem_schurInterval.mpr (by rw [mem_range] at hb; omega), by rw [mem_range] at hb; omega⟩)
      (fun _ _ => rfl)
  rw [this, sum_range_id, mul_comm]

/-- Canonical embedding of the second component $y$ into the Schur triple $(x, y, x + y)$. -/
def embedTriple (x : ℕ) : ℕ ↪ ℕ × ℕ × ℕ :=
  ⟨fun y => (x, y, x + y), fun _ _ h => by cases h; rfl⟩

/-- **Exact Counting of Monochromatic Schur Triples for $r = 1$**:
In any 1-coloring of $\{1, \dots, N\}$, the number of monochromatic Schur triples is
exactly $(N - 1) * N / 2$. -/
theorem card_monoSchurTriples_one (χ : ℕ → Fin 1) (N : ℕ) :
    (monoSchurTriples χ N).card = (N - 1) * N / 2 := by
  have h_decomp : monoSchurTriples χ N =
      (schurInterval N).biUnion (fun x => (schurInterval (N - x)).map (embedTriple x)) := by
    ext ⟨x, y, z⟩
    simp only [mem_monoSchurTriples_iff, mem_biUnion, mem_map, embedTriple, mem_schurInterval]
    constructor
    · rintro ⟨hx, hy, hz, rfl, -⟩
      exact ⟨x, hx, y, ⟨hy.1, by omega⟩, rfl⟩
    · rintro ⟨x', hx', y', ⟨hy1, hy2⟩, h_trip⟩
      cases h_trip
      exact ⟨hx', ⟨hy1, by omega⟩, ⟨by omega, by omega⟩, rfl, Subsingleton.elim _ _, Subsingleton.elim _ _⟩
  rw [h_decomp, card_biUnion]
  · simp_rw [card_map, card_schurInterval, sum_schurInterval_sub]
  · intro x1 hx1 x2 hx2 hne
    dsimp [Function.onFun]
    rw [disjoint_left]
    rintro ⟨a, b, c⟩
    simp only [mem_map, embedTriple]
    rintro ⟨y1, -, h1⟩ ⟨y2, -, h2⟩
    cases h1; cases h2; exact hne rfl

/-- For $r = 1$, if $N \ge 2k$, the number of monochromatic Schur triples is at least $k$. -/
lemma card_monoSchurTriples_one_ge_k (χ : ℕ → Fin 1) (k N : ℕ) (hN : 2 * k ≤ N) :
    k ≤ (monoSchurTriples χ N).card := by
  rw [card_monoSchurTriples_one]
  rcases k with _ | k
  · omega
  · have := Nat.mul_le_mul (show 1 ≤ N - 1 by omega) hN
    omega

/-! ### 4. Graph Ramsey Triangles & Supersaturation -/

/-- Symmetric difference coloring on $\mathbb{N}$: edges between $u$ and $v$ are colored
    by $\chi(|u - v|)$. -/
def diffColor {r : ℕ} (χ : ℕ → Fin r) (hr : 1 ≤ r) (u v : ℕ) : Fin r :=
  if u < v then χ (v - u)
  else if v < u then χ (u - v)
  else ⟨0, hr⟩

lemma diffColor_symm {r : ℕ} (χ : ℕ → Fin r) (hr : 1 ≤ r) (u v : ℕ) :
    diffColor χ hr u v = diffColor χ hr v u := by
  dsimp [diffColor]
  rcases lt_trichotomy u v with h | rfl | h
  · rw [ite_eq_left h, ite_eq_right (asymm h), ite_eq_left h]
  · rfl
  · rw [ite_eq_right (asymm h), ite_eq_left h, ite_eq_left h]

lemma diffColor_of_lt {r : ℕ} (χ : ℕ → Fin r) (hr : 1 ≤ r) {u v : ℕ} (h : u < v) :
    diffColor χ hr u v = χ (v - u) := by
  dsimp [diffColor]
  rw [ite_eq_left h]

/-- A monochromatic graph triangle in the complete graph on $\{0, \dots, N\}$ with
    difference coloring $\chi(|u - v|)$. Represented as an ordered vertex triple
    $(a, b, c)$ with $a < b < c \le N$ and $\chi(b - a) = \chi(c - b) = \chi(c - a)$. -/
def monoTriangles {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) : Finset (ℕ × ℕ × ℕ) :=
  ((range (N + 1) ×ˢ (range (N + 1) ×ˢ range (N + 1)))).filter
    (fun ⟨a, b, c⟩ => a < b ∧ b < c ∧ χ (b - a) = χ (c - b) ∧ χ (c - b) = χ (c - a))

lemma mem_monoTriangles_iff {r : ℕ} (χ : ℕ → Fin r) (N a b c : ℕ) :
    (a, b, c) ∈ monoTriangles χ N ↔
      a < b ∧ b < c ∧ c ≤ N ∧ χ (b - a) = χ (c - b) ∧ χ (c - b) = χ (c - a) := by
  simp only [monoTriangles, mem_filter, mem_product, mem_range, and_assoc]
  constructor
  · rintro ⟨ha, hb, hc, hab, hbc, hc1, hc2⟩
    exact ⟨hab, hbc, by omega, hc1, hc2⟩
  · rintro ⟨hab, hbc, hcN, hc1, hc2⟩
    exact ⟨by omega, by omega, by omega, hab, hbc, hc1, hc2⟩

/-- Any monochromatic triangle in a finite subset $S \subseteq \mathbb{N}$ under `diffColor`
    can be sorted into an ascending triple $a < b < c$ in $S$. -/
lemma sorted_triangle_of_monoTriangle {r : ℕ} (hr : 1 ≤ r) (χ : ℕ → Fin r) (S : Finset ℕ)
    (h_mono : hasMonoTriangle (diffColor χ hr) S) :
    ∃ a b c, a ∈ S ∧ b ∈ S ∧ c ∈ S ∧ a < b ∧ b < c ∧
      χ (b - a) = χ (c - b) ∧ χ (c - b) = χ (c - a) := by
  rcases h_mono with ⟨u, v, w, col, hu, hv, hw, huv, huw, hvw, hc_uv, hc_uw, hc_vw⟩
  have h_symm := diffColor_symm χ hr
  have ⟨a, b, c, ha, hb, hc, hab, hbc, hc_ab, hc_bc, hc_ac⟩ :
      ∃ a b c, a ∈ S ∧ b ∈ S ∧ c ∈ S ∧ a < b ∧ b < c ∧
        diffColor χ hr a b = col ∧ diffColor χ hr b c = col ∧ diffColor χ hr a c = col := by
    rcases lt_or_gt_of_ne huv with h1 | h1 <;>
    rcases lt_or_gt_of_ne huw with h2 | h2 <;>
    rcases lt_or_gt_of_ne hvw with h3 | h3
    · exact ⟨u, v, w, hu, hv, hw, h1, h3, hc_uv, hc_vw, hc_uw⟩
    · exact ⟨u, w, v, hu, hw, hv, h2, h3, hc_uw, by rwa [h_symm], hc_uv⟩
    · omega
    · exact ⟨w, u, v, hw, hu, hv, h2, h1, by rwa [h_symm], hc_uv, by rwa [h_symm]⟩
    · exact ⟨v, u, w, hv, hu, hw, h1, h2, by rwa [h_symm], hc_uw, hc_vw⟩
    · omega
    · exact ⟨v, w, u, hv, hw, hu, h3, h2, hc_vw, by rwa [h_symm], by rwa [h_symm]⟩
    · exact ⟨w, v, u, hw, hv, hu, h3, h1, by rwa [h_symm], by rwa [h_symm], by rwa [h_symm]⟩
  refine ⟨a, b, c, ha, hb, hc, hab, hbc, ?_⟩
  rw [diffColor_of_lt χ hr hab] at hc_ab
  rw [diffColor_of_lt χ hr hbc] at hc_bc
  rw [diffColor_of_lt χ hr (lt_trans hab hbc)] at hc_ac
  exact ⟨hc_ab.trans hc_bc.symm, hc_bc.trans hc_ac.symm⟩

/-- Shifted embedding $i \mapsto j \cdot B + i$. -/
def blockEmbed (B j : ℕ) : ℕ ↪ ℕ :=
  ⟨fun i => j * B + i, fun _ _ h => Nat.add_left_cancel h⟩

@[simp]
lemma blockEmbed_apply (B j i : ℕ) : blockEmbed B j i = j * B + i := rfl

/-- Shifted interval block $S_j = \{j \cdot B_r, \dots, (j + 1) \cdot B_r - 1\}$. -/
def intervalBlock (B : ℕ) (j : ℕ) : Finset ℕ :=
  (range B).map (blockEmbed B j)

lemma card_intervalBlock (B j : ℕ) : (intervalBlock B j).card = B := by
  dsimp [intervalBlock]; rw [card_map, card_range]

lemma mem_intervalBlock {B j x : ℕ} :
    x ∈ intervalBlock B j ↔ j * B ≤ x ∧ x < (j + 1) * B := by
  simp only [intervalBlock, mem_map, mem_range, blockEmbed_apply]
  have : (j + 1) * B = j * B + B := by ring
  constructor
  · rintro ⟨i, hi, rfl⟩; omega
  · intro ⟨h1, h2⟩; exact ⟨x - j * B, by omega, by omega⟩

/-- **Supersaturation of Graph Triangles**:
For any $r \ge 1$, $k \ge 1$, and $N + 1 \ge k \cdot \text{ramseyTriangleBound } r$,
the number of monochromatic graph triangles in $\{0, \dots, N\}$ is at least $k$. -/
theorem card_monoTriangles_ge_k (r : ℕ) (hr : 1 ≤ r) (χ : ℕ → Fin r) (k N : ℕ)
    (hN : k * ramseyTriangleBound r ≤ N + 1) :
    k ≤ (monoTriangles χ N).card := by
  let B := ramseyTriangleBound r
  have h_triangle_in_block : ∀ j < k,
      ∃ a b c, a < b ∧ b < c ∧ c ≤ N ∧
        χ (b - a) = χ (c - b) ∧ χ (c - b) = χ (c - a) ∧
        j * B ≤ a ∧ a < (j + 1) * B := by
    intro j hj
    let Sj := intervalBlock B j
    have h_mono : hasMonoTriangle (diffColor χ hr) Sj :=
      ramsey_triangle r hr Sj (diffColor χ hr) (diffColor_symm χ hr) (by rw [card_intervalBlock])
    rcases sorted_triangle_of_monoTriangle hr χ Sj h_mono with
      ⟨a, b, c, ha, hb, hc, hab, hbc, hc_diff1, hc_diff2⟩
    rw [mem_intervalBlock] at ha hc
    have hcN : c ≤ N := by
      have : (j + 1) * B ≤ N + 1 := le_trans (Nat.mul_le_mul_right B (by omega)) hN
      omega
    exact ⟨a, b, c, hab, hbc, hcN, hc_diff1, hc_diff2, ha.1, ha.2⟩
  choose! a_of b_of c_of hab_of hbc_of hcN_of hc1_of hc2_of ha_ge_of ha_lt_of using h_triangle_in_block
  let trip (j : ℕ) : ℕ × ℕ × ℕ := (a_of j, b_of j, c_of j)
  have h_le := card_le_card_of_injOn trip
    (fun j hj => mem_coe.mpr (mem_monoTriangles_iff χ N _ _ _ |>.mpr
      ⟨hab_of j (mem_range.mp hj), hbc_of j (mem_range.mp hj), hcN_of j (mem_range.mp hj),
       hc1_of j (mem_range.mp hj), hc2_of j (mem_range.mp hj)⟩))
    (fun j1 hj1 j2 hj2 heq => by
      have hj1_lt := mem_range.mp hj1; have hj2_lt := mem_range.mp hj2
      injection heq with ha_eq _
      have h1 := ha_ge_of j1 hj1_lt; have h2 := ha_lt_of j1 hj1_lt
      have h3 := ha_ge_of j2 hj2_lt; have h4 := ha_lt_of j2 hj2_lt
      by_contra! hne
      rcases lt_or_gt_of_ne hne with hlt | hgt
      · have : (j1 + 1) * B ≤ j2 * B := Nat.mul_le_mul_right B (by omega); omega
      · have : (j2 + 1) * B ≤ j1 * B := Nat.mul_le_mul_right B (by omega); omega)
  rwa [card_range] at h_le

/-- The projection mapping each ordered monochromatic graph triangle `(a, b, c)`
    to its corresponding monochromatic Schur difference triple `(b - a, c - b, c - a)`. -/
def triangleToSchurTriple : ℕ × ℕ × ℕ → ℕ × ℕ × ℕ :=
  fun ⟨a, b, c⟩ => (b - a, c - b, c - a)

lemma triangleToSchurTriple_mem {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) {a b c : ℕ}
    (h : (a, b, c) ∈ monoTriangles χ N) :
    triangleToSchurTriple (a, b, c) ∈ monoSchurTriples χ N := by
  rw [mem_monoTriangles_iff] at h
  rcases h with ⟨hab, hbc, hcN, hc1, hc2⟩
  exact mem_monoSchurTriples_iff χ N (b - a) (c - b) (c - a) |>.mpr
    ⟨mem_schurInterval.mpr ⟨by omega, by omega⟩,
     mem_schurInterval.mpr ⟨by omega, by omega⟩,
     mem_schurInterval.mpr ⟨by omega, by omega⟩,
     by omega, hc1, hc2⟩

/-- Upper bound on the fiber of each Schur triple under `triangleToSchurTriple`:
    each Schur triple `(x, y, z)` can arise from at most `N` graph triangles in `{0, ..., N}`. -/
lemma card_fiber_triangleToSchurTriple_le {r : ℕ} (χ : ℕ → Fin r) (N : ℕ)
    (trip : ℕ × ℕ × ℕ) (htrip : trip ∈ monoSchurTriples χ N) :
    ((monoTriangles χ N).filter (fun t => triangleToSchurTriple t = trip)).card ≤ N := by
  rcases trip with ⟨x, y, z⟩
  rw [mem_monoSchurTriples_iff] at htrip
  rcases htrip with ⟨-, -, hz, -⟩
  rw [mem_schurInterval] at hz
  let proj : ℕ × ℕ × ℕ → ℕ := fun ⟨a, _, _⟩ => a
  have h_le := card_le_card_of_injOn (s := (monoTriangles χ N).filter (fun t => triangleToSchurTriple t = (x, y, z)))
    (t := range N) proj
    (fun ⟨a, b, c⟩ h => by
      rw [mem_coe, mem_filter, mem_monoTriangles_iff] at h
      rcases h with ⟨⟨hab, hbc, hcN, -⟩, heq⟩
      dsimp [triangleToSchurTriple, proj] at heq ⊢
      injection heq with _ h_rest; injection h_rest with _ h_z
      have : c = a + z := by omega
      exact mem_coe.mpr (mem_range.mpr (by omega)))
    (fun ⟨a1, b1, c1⟩ h1 ⟨a2, b2, c2⟩ h2 heq => by
      rw [mem_coe, mem_filter, mem_monoTriangles_iff] at h1 h2
      rcases h1 with ⟨⟨hab1, hbc1, -, -⟩, heq1⟩
      rcases h2 with ⟨⟨hab2, hbc2, -, -⟩, heq2⟩
      dsimp [triangleToSchurTriple, proj] at heq1 heq2 heq
      injection heq1 with heq1_x h_rest1; injection h_rest1 with _ heq1_z
      injection heq2 with heq2_x h_rest2; injection h_rest2 with _ heq2_z
      have hb1 : b1 = a1 + x := by omega
      have hc1 : c1 = a1 + z := by omega
      have hb2 : b2 = a2 + x := by omega
      have hc2 : c2 = a2 + z := by omega
      subst heq hb1 hc1 hb2 hc2; rfl)
  rwa [card_range] at h_le

/-- **Double Counting Relation Between Graph Triangles and Schur Triples**:
The number of monochromatic graph triangles in $\{0, \dots, N\}$ is bounded above by
$N$ times the number of monochromatic Schur triples in $\{1, \dots, N\}$. -/
theorem card_monoTriangles_le_mul_card_monoSchurTriples {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) :
    (monoTriangles χ N).card ≤ N * (monoSchurTriples χ N).card :=
  card_le_mul_card_image_of_maps_to (fun _ => triangleToSchurTriple_mem χ N) N
    (fun b hb => card_fiber_triangleToSchurTriple_le χ N b hb)

/-- **Quantitative Disjoint-Block Double-Counting Bound**:
For any $r \ge 1$, $k \ge 1$, and $N \ge k \cdot \text{ramseyTriangleBound } r$,
the double counting between $k$ disjoint graph triangles in $\{0, \dots, N\}$ and integer Schur difference triples
yields:
$$k \le N \cdot |\text{monoSchurTriples } \chi N|$$
This quantitative disjoint-block double-counting bound relates the number $k$ of disjoint blocks of size $B_r$
to the count of monochromatic Schur triples. In contrast, for $r = 1$, `card_monoSchurTriples_one`
establishes the exact quadratic density $\frac{(N-1)N}{2} = \frac{1}{2}N^2 - \frac{1}{2}N$. -/
theorem supersaturation_bound (r : ℕ) (hr : 1 ≤ r) (χ : ℕ → Fin r) (k N : ℕ)
    (hN : k * ramseyTriangleBound r ≤ N) :
    k ≤ N * (monoSchurTriples χ N).card :=
  (card_monoTriangles_ge_k r hr χ k N (by omega)).trans
    (card_monoTriangles_le_mul_card_monoSchurTriples χ N)

/-! ### 5. Color Class Formulation & Partition Additive Energy -/

/-- Monochromatic Schur triples of a specific color `c ∈ Fin r`. -/
def monoSchurTriplesColor {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) (c : Fin r) : Finset (ℕ × ℕ × ℕ) :=
  (monoSchurTriples χ N).filter (fun ⟨x, _, _⟩ => χ x = c)

lemma mem_monoSchurTriplesColor_iff {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) (c : Fin r) (x y z : ℕ) :
    (x, y, z) ∈ monoSchurTriplesColor χ N c ↔
      x ∈ schurInterval N ∧ y ∈ schurInterval N ∧ z ∈ schurInterval N ∧
      x + y = z ∧ χ x = c ∧ χ y = c ∧ χ z = c := by
  simp only [monoSchurTriplesColor, mem_filter, mem_monoSchurTriples_iff]
  constructor
  · rintro ⟨⟨hx, hy, hz, hsum, hc1, hc2⟩, hcx⟩
    exact ⟨hx, hy, hz, hsum, hcx, by rwa [← hc1], by rwa [← hc2, ← hc1]⟩
  · rintro ⟨hx, hy, hz, hsum, hcx, hcy, hcz⟩
    exact ⟨⟨hx, hy, hz, hsum, hcx.trans hcy.symm, hcy.trans hcz.symm⟩, hcx⟩

/-- Partition of `monoSchurTriples` into disjoint monochromatic color classes. -/
theorem monoSchurTriples_eq_biUnion_color {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) :
    monoSchurTriples χ N = Finset.univ.biUnion (fun c => monoSchurTriplesColor χ N c) := by
  ext ⟨x, y, z⟩
  simp only [mem_monoSchurTriples_iff, mem_biUnion, mem_univ, true_and,
             mem_monoSchurTriplesColor_iff]
  constructor
  · rintro ⟨hx, hy, hz, hsum, hc1, hc2⟩
    exact ⟨χ x, hx, hy, hz, hsum, rfl, hc1.symm, (hc1.trans hc2).symm⟩
  · rintro ⟨c, hx, hy, hz, hsum, hcx, hcy, hcz⟩
    exact ⟨hx, hy, hz, hsum, hcx.trans hcy.symm, hcy.trans hcz.symm⟩

/-- Sum formula decomposing the total count into color classes. -/
theorem card_monoSchurTriples_eq_sum_color {r : ℕ} (χ : ℕ → Fin r) (N : ℕ) :
    (monoSchurTriples χ N).card = ∑ c : Fin r, (monoSchurTriplesColor χ N c).card := by
  rw [monoSchurTriples_eq_biUnion_color, card_biUnion]
  intro c1 _ c2 _ hne
  dsimp [Function.onFun]
  rw [Finset.disjoint_left]
  rintro ⟨x, y, z⟩ h1 h2
  rw [mem_monoSchurTriplesColor_iff] at h1 h2
  exact hne (h1.2.2.2.2.1.symm.trans h2.2.2.2.2.1)

/-- At least one color class contains a monochromatic Schur triple when $N \ge B_r$. -/
theorem exists_color_with_monoSchurTriple (r : ℕ) (hr : 1 ≤ r) (χ : ℕ → Fin r) (N : ℕ)
    (hN : ramseyTriangleBound r ≤ N) :
    ∃ c : Fin r, 1 ≤ (monoSchurTriplesColor χ N c).card := by
  rcases monoSchurTriples_nonempty r hr χ N hN with ⟨⟨x, y, z⟩, h_trip⟩
  rw [mem_monoSchurTriples_iff] at h_trip
  rcases h_trip with ⟨hx, hy, hz, hsum, hc1, hc2⟩
  refine ⟨χ x, card_pos.mpr ⟨(x, y, z), ?_⟩⟩
  rw [mem_monoSchurTriplesColor_iff]
  exact ⟨hx, hy, hz, hsum, rfl, hc1.symm, (hc1.trans hc2).symm⟩

#print axioms monoSchurTriples_nonempty
#print axioms card_monoSchurTriples_ge_one
#print axioms card_monoSchurTriples_one
#print axioms card_monoTriangles_ge_k
#print axioms card_monoTriangles_le_mul_card_monoSchurTriples
#print axioms supersaturation_bound
#print axioms card_monoSchurTriples_eq_sum_color
#print axioms exists_color_with_monoSchurTriple

end SchursTheorem